apiVersion: batch/v1
kind: Job
metadata:
  name: install-kernels-copy-defaults
  namespace: enterprise-gateway
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: installer
        # MUST use the Elyra image to have access to the source kernels
        image: elyra/enterprise-gateway:3.2.3  
        command: ["/bin/sh", "-c"]
        securityContext:
          runAsUser: 0
        args:
          - |
            echo "==============================================="
            echo "   STARTING KERNEL CLEAN & MIGRATION PROCESS   "
            echo "==============================================="
            
            SOURCE_DEFAULTS="/usr/local/share/jupyter/kernels"
            TARGET_DIR="/mnt/pvc"

            # --- STEP 1: CLEANUP ---
            echo "[1/3] Cleaning target directory ($TARGET_DIR)..."
            # Wipes everything in the PVC to ensure a fresh start
            rm -rf $TARGET_DIR/*
            echo "      Clean complete."

            # --- STEP 2: COPY DEFAULT KERNELS ---
            echo "[2/3] Copying Default Kernels..."
            KERNELS_TO_COPY="r_kubernetes python_kubernetes python_tf_kubernetes scala_kubernetes spark_r_kubernetes spark_python_kubernetes spark_scala_kubernetes spark_python_operator"

            for KERNEL in $KERNELS_TO_COPY; do
              if [ -d "$SOURCE_DEFAULTS/$KERNEL" ]; then
                echo "      + Copying: $KERNEL"
                cp -r "$SOURCE_DEFAULTS/$KERNEL" "$TARGET_DIR/"
              else
                echo "      ! WARNING: Could not find '$KERNEL' in image default path!"
              fi
            done

            # --- STEP 3: INSTALL CUSTOM GPU KERNELS ---
            echo "[3/3] Installing Custom GPU Sharing Kernels..."

            install_custom_kernel() {
              SRC=$1
              NAME=$2
              DEST="$TARGET_DIR/$NAME"
              
              echo "      + Installing: $NAME"
              mkdir -p $DEST
              cp $SRC/kernel.json $DEST/
              cp $SRC/kernel-pod.yaml.j2 $DEST/
              cp $SRC/launch_kubernetes.py $DEST/
              chmod +x $DEST/launch_kubernetes.py
            }

            install_custom_kernel "/mnt/configmap-pytorch-4gb" "pytorch_gpu_sharing_4GB"
            install_custom_kernel "/mnt/configmap-tf-4gb" "tf_gpu_sharing_4GB"
            install_custom_kernel "/mnt/configmap-pytorch-8gb" "pytorch_gpu_sharing_8GB"
            install_custom_kernel "/mnt/configmap-tf-8gb" "tf_gpu_sharing_8GB"

            echo "==============================================="
            echo "   MIGRATION COMPLETE. FINAL CONTENTS:         "
            echo "==============================================="
            ls -F $TARGET_DIR

        volumeMounts:
        - name: kernels-pvc
          mountPath: /mnt/pvc
        - name: cm-pytorch-4gb
          mountPath: /mnt/configmap-pytorch-4gb
        - name: cm-tf-4gb
          mountPath: /mnt/configmap-tf-4gb
        - name: cm-pytorch-8gb
          mountPath: /mnt/configmap-pytorch-8gb
        - name: cm-tf-8gb
          mountPath: /mnt/configmap-tf-8gb

      volumes:
      - name: kernels-pvc
        persistentVolumeClaim:
          claimName: kernel-specs-pvc
      - name: cm-pytorch-4gb
        configMap:
          name: kernel-spec-pytorch-gpu-4gb
      - name: cm-tf-4gb
        configMap:
          name: kernel-spec-tf-gpu-4gb
      - name: cm-pytorch-8gb
        configMap:
          name: kernel-spec-pytorch-gpu-8gb
      - name: cm-tf-8gb
        configMap:
          name: kernel-spec-tf-gpu-8gb

      restartPolicy: OnFailure